#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("legalpro_cuestionarios.Resource", IsApplication=true)]

namespace legalpro_cuestionarios
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int click = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int movimientolento = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int movimientolento5p = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int pushb = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int rotar = 2130968580;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cancelar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cuadrito = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cuadrot = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int descargar = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int edit = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int fondoa = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int fondoa2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int guardar = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int lista = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int logolegalpro = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int loguito = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int nube = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int nuevo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ok = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int pajara = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int siguiente = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001c
			public const int button = 2131099676;
			
			// aapt resource value: 0x7f06000f
			public const int buttona = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int buttonc = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int buttonf = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int buttonx = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int cargando = 2131099665;
			
			// aapt resource value: 0x7f06001f
			public const int descargar = 2131099679;
			
			// aapt resource value: 0x7f060014
			public const int descripcion = 2131099668;
			
			// aapt resource value: 0x7f06000b
			public const int fotolayout = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int g_nube = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int guardar = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int imageButton = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int imageView = 2131099650;
			
			// aapt resource value: 0x7f060019
			public const int imageView2 = 2131099673;
			
			// aapt resource value: 0x7f060004
			public const int imageView4 = 2131099652;
			
			// aapt resource value: 0x7f06000c
			public const int imageViewfoto = 2131099660;
			
			// aapt resource value: 0x7f06001a
			public const int legalpro = 2131099674;
			
			// aapt resource value: 0x7f060020
			public const int lista = 2131099680;
			
			// aapt resource value: 0x7f06000a
			public const int listaa = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int listam = 2131099657;
			
			// aapt resource value: 0x7f060012
			public const int logito = 2131099666;
			
			// aapt resource value: 0x7f060018
			public const int nube = 2131099672;
			
			// aapt resource value: 0x7f06001e
			public const int nuevo = 2131099678;
			
			// aapt resource value: 0x7f060017
			public const int opciones = 2131099671;
			
			// aapt resource value: 0x7f06001d
			public const int password = 2131099677;
			
			// aapt resource value: 0x7f060000
			public const int relativeLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060016
			public const int resultado = 2131099670;
			
			// aapt resource value: 0x7f060003
			public const int siguiente = 2131099651;
			
			// aapt resource value: 0x7f060021
			public const int spinnerTarget = 2131099681;
			
			// aapt resource value: 0x7f060015
			public const int templatt = 2131099669;
			
			// aapt resource value: 0x7f060007
			public const int terminado = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int textView3 = 2131099656;
			
			// aapt resource value: 0x7f060013
			public const int titulo = 2131099667;
			
			// aapt resource value: 0x7f06001b
			public const int usuario = 2131099675;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Cuestionario = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Descargar = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Lista = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int lista1 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int lista2 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Lista3 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Lista_disponibles = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Lista_guardados = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Mainwindow = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int spinner_kayout = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
